version: 2

sources:
  - name: paralex_raw    # A nickname we give this group of tables
    database: paralex    # The actual DB name in Postgres
    schema: public       # The schema where Airflow put the data
    tables:
      - name: french_processed
      - name: italian_processed
      - name: portuguese_processed
      - name: spanish_processed
      - name: romanian_processed